In [3]:
from bs4 import BeautifulSoup
import requests

res=requests.get(f"https://www.worldometers.info/coronavirus/",'html.parser')
data=res.text
soup=BeautifulSoup(data,'lxml')

table_tag=soup.find('table')
table_tag

<table class="table table-bordered table-hover main_table_countries" id="main_table_countries_today" style="width:100%;margin-top: 0px !important;display:none;">
<thead>
<tr>
<th width="1%">#</th>
<th width="100">Country,<br/>Other</th>
<th width="20">Total<br/>Cases</th>
<th width="30">New<br/>Cases</th>
<th width="30">Total<br/>Deaths</th>
<th width="30">New<br/>Deaths</th>
<th width="30">Total<br/>Recovered</th>
<th width="30">New<br/>Recovered</th>
<th width="30">Active<br/>Cases</th>
<th width="30">Serious,<br/>Critical</th>
<th width="30">TotÂ Cases/<br/>1M pop</th>
<th width="30">Deaths/<br/>1M pop</th>
<th width="30">Total<br/>Tests</th>
<th width="30">Tests/<br/>
<nobr>1M pop</nobr>
</th>
<th width="30">Population</th>
<th style="display:none" width="30">Continent</th>
<th width="30">1 Case<br/>every X ppl</th><th width="30">1 Death<br/>every X ppl</th><th width="30">1 Test<br/>every X ppl</th>
</tr>
</thead>
<tbody>
<tr class="total_row_world row_continent" data-continent="North America" style="display: none">
<td></td>
<td style="text-align:left;">
<nobr>North America</nobr>
</td>
<td>2,282,663</td>
<td>+4,183</td>
<td>135,758</td>
<td>+221</td>
<td>930,353</td>
<td>+3,056</td>
<td>1,216,552</td>
<td>19,428</td>
<td></td>
<td></td>
<td></td>
<td></td>
<td></td>
<td data-continent="North America" style="display:none;">North America</td>
<td>
</td>
<td></td>
<td></td>
</tr>
<tr class="total_row_world row_continent" data-continent="South America" style="display: none">
<td></td>
<td style="text-align:left;">
<nobr>South America</nobr>
</td>
<td>1,146,755</td>
<td>+285</td>
<td>51,046</td>
<td>+824</td>
<td>531,548</td>
<td>+184</td>
<td>564,161</td>
<td>11,783</td>
<td></td>
<td></td>
<td></td>
<td></td>
<td></td>
<td data-continent="South America" style="display:none;">South America</td>
<td>
</td>
<td></td>
<td></td>
</tr>
<tr class="total_row_world row_continent" data-continent="Europe" style="display: none">
<td></td>
<td style="text-align:left;">
<nobr>Europe</nobr>
</td>
<td>2,094,794</td>
<td>+486</td>
<td>178,956</td>
<td>+13</td>
<td>1,082,922</td>
<td>+794</td>
<td>832,916</td>
<td>7,181</td>
<td></td>
<td></td>
<td></td>
<td></td>
<td></td>
<td data-continent="Europe" style="display:none;">Europe</td>
<td>
</td>
<td></td>
<td></td>
</tr>
<tr class="total_row_world row_continent" data-continent="Asia" style="display: none">
<td></td>
<td style="text-align:left;">
<nobr>Asia</nobr>
</td>
<td>1,368,045</td>
<td>+6,816</td>
<td>35,117</td>
<td>+92</td>
<td>823,887</td>
<td>+1,591</td>
<td>509,041</td>
<td>14,880</td>
<td></td>
<td></td>
<td></td>
<td></td>
<td></td>
<td data-continent="Asia" style="display:none;">Asia</td>
<td>
</td>
<td></td>
<td></td>
</tr>
<tr class="total_row_world row_continent" data-continent="Africa" style="display: none">
<td></td>
<td style="text-align:left;">
<nobr>Africa</nobr>
</td>
<td>192,118</td>
<td></td>
<td>5,215</td>
<td></td>
<td>84,919</td>
<td></td>
<td>101,984</td>
<td>469</td>
<td></td>
<td></td>
<td></td>
<td></td>
<td></td>
<td data-continent="Africa" style="display:none;">Africa</td>
<td>
</td>
<td></td>
<td></td>
</tr>
<tr class="total_row_world row_continent" data-continent="Australia/Oceania" style="display: none">
<td></td>
<td style="text-align:left;">
<nobr>Oceania</nobr>
</td>
<td>8,875</td>
<td>+5</td>
<td>124</td>
<td></td>
<td>8,293</td>
<td>+4</td>
<td>458</td>
<td>3</td>
<td></td>
<td></td>
<td></td>
<td></td>
<td></td>
<td data-continent="Australia/Oceania" style="display:none;">Australia/Oceania</td>
<td>
</td>
<td></td>
<td></td>
</tr>
<tr class="total_row_world row_continent" data-continent="" style="display: none">
<td></td>
<td style="text-align:left;">
<nobr></nobr>
</td>
<td>721</td>
<td></td>
<td>15</td>
<td></td>
<td>651</td>
<td></td>
<td>55</td>
<td>4</td>
<td></td>
<td></td>
<td></td>
<td></td>
<td></td>
<td data-continent="" style="display:none;"></td>
<td>
</td>
<td></td>
<td></td>
</tr>
<tr class="total_row_world">
<td></td>
<td style="text-align:left;">World</td>
<td>7,093,971</td>
<td>+11,775</td>
<td>406,231</td>
<td>+1,150</td>
<td>3,462,573</td>
<td>+5,629</td>
<td>3,225,167</td>
<td>53,748</td>
<td>910</td>
<td>52.1</td>
<td></td>
<td></td>
<td></td>
<td data-continent="all" style="display:none">All</td>
<td>
</td>
<td></td>
<td></td>
</tr>
<tr style="">
<td style="font-size:12px;color: grey;text-align:center;vertical-align:middle;">1</td>
<td style="font-weight: bold; font-size:15px; text-align:left;"><a class="mt_a" href="country/us/">USA</a></td>
<td style="font-weight: bold; text-align:right">2,007,449</td>
<td style="font-weight: bold; text-align:right;"></td>
<td style="font-weight: bold; text-align:right;">112,469 </td>
<td style="font-weight: bold;
                                    text-align:right;"></td>
<td style="font-weight: bold; text-align:right">761,708</td>
<td style="font-weight: bold; text-align:right;"></td>
<td style="text-align:right;font-weight:bold;">1,133,272</td>
<td style="font-weight: bold; text-align:right">16,923</td>
<td style="font-weight: bold; text-align:right">6,067</td>
<td style="font-weight: bold; text-align:right">340</td>
<td style="font-weight: bold; text-align:right">21,291,677</td>
<td style="font-weight: bold; text-align:right">64,349</td>
<td style="font-weight: bold; text-align:right"><a href="/world-population/us-population/">330,880,530</a> </td>
<td data-continent="North America" style="display:none">North America</td>
<td>165</td><td>2,942</td><td>16</td>
</tr>
<tr style="">
<td style="font-size:12px;color: grey;text-align:center;vertical-align:middle;">2</td>
<td style="font-weight: bold; font-size:15px; text-align:left;"><a class="mt_a" href="country/brazil/">Brazil</a></td>
<td style="font-weight: bold; text-align:right">691,962</td>
<td style="font-weight: bold; text-align:right;"></td>
<td style="font-weight: bold; text-align:right;">37,312 </td>
<td style="font-weight: bold;
                                    text-align:right;background-color:red; color:white">+813</td>
<td style="font-weight: bold; text-align:right">302,084</td>
<td style="font-weight: bold; text-align:right;"></td>
<td style="text-align:right;font-weight:bold;">352,566</td>
<td style="font-weight: bold; text-align:right">8,318</td>
<td style="font-weight: bold; text-align:right">3,257</td>
<td style="font-weight: bold; text-align:right">176</td>
<td style="font-weight: bold; text-align:right">999,836</td>
<td style="font-weight: bold; text-align:right">4,706</td>
<td style="font-weight: bold; text-align:right"><a href="/world-population/brazil-population/">212,463,372</a> </td>
<td data-continent="South America" style="display:none">South America</td>
<td>307</td><td>5,694</td><td>212</td>
</tr>
<tr style="">
<td style="font-size:12px;color: grey;text-align:center;vertical-align:middle;">3</td>
<td style="font-weight: bold; font-size:15px; text-align:left;"><a class="mt_a" href="country/russia/">Russia</a></td>
<td style="font-weight: bold; text-align:right">467,673</td>
<td style="font-weight: bold; text-align:right;"></td>
<td style="font-weight: bold; text-align:right;">5,859 </td>
<td style="font-weight: bold;
                                    text-align:right;"></td>
<td style="font-weight: bold; text-align:right">226,731</td>
<td style="font-weight: bold; text-align:right;"></td>
<td style="text-align:right;font-weight:bold;">235,083</td>
<td style="font-weight: bold; text-align:right">2,300</td>
<td style="font-weight: bold; text-align:right">3,205</td>
<td style="font-weight: bold; text-align:right">40</td>
<td style="font-weight: bold; text-align:right">12,721,549</td>
<td style="font-weight: bold; text-align:right">87,175</td>
<td style="font-weight: bold; text-align:right"><a href="/world-population/russia-population/">145,930,700</a> </td>
<td data-continent="Europe" style="display:none">Europe</td>
<td>312</td><td>24,907</td><td>11</td>
</tr>
<tr style="">
<td style="font-size:12px;color: grey;text-align:center;vertical-align:middle;">4</td>
<td style="font-weight: bold; font-size:15px; text-align:left;"><a class="mt_a" href="country/spain/">Spain</a></td>
<td style="font-weight: bold; text-align:right">288,630</td>
<td style="font-weight: bold; text-align:right;"></td>
<td style="font-weight: bold; text-align:right;">27,136 </td>
<td style="font-weight: bold;
                                    text-align:right;"></td>
<td style="font-weight: bold; text-align:right">N/A</td>
<td style="font-weight: bold; text-align:right;">N/A</td>
<td style="text-align:right;font-weight:bold;">N/A</td>
<td style="font-weight: bold; text-align:right">617</td>
<td style="font-weight: bold; text-align:right">6,173</td>
<td style="font-weight: bold; text-align:right">580</td>
<td style="font-weight: bold; text-align:right">4,063,843</td>
<td style="font-weight: bold; text-align:right">86,920</td>
<td style="font-weight: bold; text-align:right"><a href="/world-population/spain-population/">46,753,690</a> </td>
<td data-continent="Europe" style="display:none">Europe</td>
<td>162</td><td>1,723</td><td>12</td>
</tr>
<tr style="">
<td style="font-size:12px;color: grey;text-align:center;vertical-align:middle;">5</td>
<td style="font-weight: bold; font-size:15px; text-align:left;"><a class="mt_a" href="country/uk/">UK</a></td>
<td style="font-weight: bold; text-align:right">286,194</td>
<td style="font-weight: bold; text-align:right;"></td>
<td style="font-weight: bold; text-align:right;">40,542 </td>
<td style="font-weight: bold;
                                    text-align:right;"></td>
<td style="font-weight: bold; text-align:right">N/A</td>
<td style="font-weight: bold; text-align:right;">N/A</td>
<td style="text-align:right;font-weight:bold;">N/A</td>
<td style="font-weight: bold; text-align:right">604</td>
<td style="font-weight: bold; text-align:right">4,217</td>
<td style="font-weight: bold; text-align:right">597</td>
<td style="font-weight: bold; text-align:right">5,581,073</td>
<td style="font-weight: bold; text-align:right">82,239</td>
<td style="font-weight: bold; text-align:right"><a href="/world-population/uk-population/">67,863,688</a> </td>
<td data-continent="Europe" style="display:none">Europe</td>
<td>237</td><td>1,674</td><td>12</td>
</tr>
<tr style="">
<td style="font-size:12px;color: grey;text-align:center;vertical-align:middle;">6</td>
<td style="font-weight: bold; font-size:15px; text-align:left;"><a class="mt_a" href="country/india/">India</a></td>
<td style="font-weight: bold; text-align:right">258,090</td>
<td style="font-weight: bold; text-align:right;background-color:#FFEEAA;">+604</td>
<td style="font-weight: bold; text-align:right;">7,207 </td>
<td style="font-weight: bold;
                                    text-align:right;"></td>
<td style="font-weight: bold; text-align:right">124,095</td>
<td style="font-weight: bold; text-align:right;background-color:#c8e6c9; color:#000">+247</td>
<td style="text-align:right;font-weight:bold;">126,788</td>
<td style="font-weight: bold; text-align:right">8,944</td>
<td style="font-weight: bold; text-align:right">187</td>
<td style="font-weight: bold; text-align:right">5</td>
<td style="font-weight: bold; text-align:right">4,774,434</td>
<td style="font-weight: bold; text-align:right">3,462</td>
<td style="font-weight: bold; text-align:right"><a href="/world-population/india-population/">1,379,122,578</a> </td>
<td data-continent="Asia" style="display:none">Asia</td>
<td>5,344</td><td>191,359</td><td>289</td>
</tr>
<tr style="">
<td style="font-size:12px;color: grey;text-align:center;vertical-align:middle;">7</td>
<td style="font-weight: bold; font-size:15px; text-align:left;"><a class="mt_a" href="country/italy/">Italy</a></td>
<td style="font-weight: bold; text-align:right">234,998</td>
<td style="font-weight: bold; text-align:right;"></td>
<td style="font-weight: bold; text-align:right;">33,899 </td>
<td style="font-weight: bold;
                                    text-align:right;"></td>
<td style="font-weight: bold; text-align:right">165,837</td>
<td style="font-weight: bold; text-align:right;"></td>
<td style="text-align:right;font-weight:bold;">35,262</td>
<td style="font-weight: bold; text-align:right">287</td>
<td style="font-weight: bold; text-align:right">3,886</td>
<td style="font-weight: bold; text-align:right">561</td>
<td style="font-weight: bold; text-align:right">4,236,535</td>
<td style="font-weight: bold; text-align:right">70,063</td>
<td style="font-weight: bold; text-align:right"><a href="/world-population/italy-population/">60,467,085</a> </td>
<td data-continent="Europe" style="display:none">Europe</td>
<td>257</td><td>1,784</td><td>14</td>
</tr>
<tr style="">
<td style="font-size:12px;color: grey;text-align:center;vertical-align:middle;">8</td>
<td style="font-weight: bold; font-size:15px; text-align:left;"><a class="mt_a" href="country/peru/">Peru</a></td>
<td style="font-weight: bold; text-align:right">196,515</td>
<td style="font-weight: bold; text-align:right;"></td>
<td style="font-weight: bold; text-align:right;">5,465 </td>
<td style="font-weight: bold;
                                    text-align:right;"></td>
<td style="font-weight: bold; text-align:right">86,219</td>
<td style="font-weight: bold; text-align:right;"></td>
<td style="text-align:right;font-weight:bold;">104,831</td>
<td style="font-weight: bold; text-align:right">1,062</td>
<td style="font-weight: bold; text-align:right">5,966</td>
<td style="font-weight: bold; text-align:right">166</td>
<td style="font-weight: bold; text-align:right">1,191,956</td>
<td style="font-weight: bold; text-align:right">36,185</td>
<td style="font-weight: bold; text-align:right"><a href="/world-population/peru-population/">32,941,004</a> </td>
<td data-continent="South America" style="display:none">South America</td>
<td>168</td><td>6,028</td><td>28</td>
</tr>
<tr style="">
<td style="font-size:12px;color: grey;text-align:center;vertical-align:middle;">9</td>
<td style="font-weight: bold; font-size:15px; text-align:left;"><a class="mt_a" href="country/germany/">Germany</a></td>
<td style="font-weight: bold; text-align:right">185,869</td>
<td style="font-weight: bold; text-align:right;"></td>
<td style="font-weight: bold; text-align:right;">8,776 </td>
<td style="font-weight: bold;
                                    text-align:right;"></td>
<td style="font-weight: bold; text-align:right">169,600</td>
<td style="font-weight: bold; text-align:right;background-color:#c8e6c9; color:#000">+500</td>
<td style="text-align:right;font-weight:bold;">7,493</td>
<td style="font-weight: bold; text-align:right">568</td>
<td style="font-weight: bold; text-align:right">2,219</td>
<td style="font-weight: bold; text-align:right">105</td>
<td style="font-weight: bold; text-align:right">4,348,880</td>
<td style="font-weight: bold; text-align:right">51,916</td>
<td style="font-weight: bold; text-align:right"><a href="/world-population/germany-population/">83,767,456</a> </td>
<td data-continent="Europe" style="display:none">Europe</td>
<td>451</td><td>9,545</td><td>19</td>
</tr>
<tr style="">
<td style="font-size:12px;color: grey;text-align:center;vertical-align:middle;">10</td>
<td style="font-weight: bold; font-size:15px; text-align:left;"><a class="mt_a" href="country/iran/">Iran</a></td>
<td style="font-weight: bold; text-align:right">171,789</td>
<td style="font-weight: bold; text-align:right;"></td>
<td style="font-weight: bold; text-align:right;">8,281 </td>
<td style="font-weight: bold;
                                    text-align:right;"></td>
<td style="font-weight: bold; text-align:right">134,349</td>
<td style="font-weight: bold; text-align:right;"></td>
<td style="text-align:right;font-weight:bold;">29,159</td>
<td style="font-weight: bold; text-align:right">2,596</td>
<td style="font-weight: bold; text-align:right">2,047</td>
<td style="font-weight: bold; text-align:right">99</td>
<td style="font-weight: bold; text-align:right">1,084,857</td>
<td style="font-weight: bold; text-align:right">12,927</td>
<td style="font-weight: bold; text-align:right"><a href="/world-population/iran-population/">83,921,387</a> </td>
<td data-continent="Asia" style="display:none">Asia</td>
<td>489</td><td>10,134</td><td>77</td>
</tr>
<tr style="">
<td style="font-size:12px;color: grey;text-align:center;vertical-align:middle;">11</td>
<td style="font-weight: bold; font-size:15px; text-align:left;"><a class="mt_a" href="country/turkey/">Turkey</a></td>
<td style="font-weight: bold; text-align:right">170,132</td>
<td style="font-weight: bold; text-align:right;"></td>
<td style="font-weight: bold; text-align:right;">4,692 </td>
<td style="font-weight: bold;
                                    text-align:right;"></td>
<td style="font-weight: bold; text-align:right">137,969</td>
<td style="font-weight: bold; text-align:right;"></td>
<td style="text-align:right;font-weight:bold;">27,471</td>
<td style="font-weight: bold; text-align:right">613</td>
<td style="font-weight: bold; text-align:right">2,019</td>
<td style="font-weight: bold; text-align:right">56</td>
<td style="font-weight: bold; text-align:right">2,338,593</td>
<td style="font-weight: bold; text-align:right">27,748</td>
<td style="font-weight: bold; text-align:right"><a href="/world-population/turkey-population/">84,279,639</a> </td>
<td data-continent="Asia" style="display:none">Asia</td>
<td>495</td><td>17,962</td><td>36</td>
</tr>
<tr style="">
<td style="font-size:12px;color: grey;text-align:center;vertical-align:middle;">12</td>
<td style="font-weight: bold; font-size:15px; text-align:left;"><a class="mt_a" href="country/france/">France</a></td>
<td style="font-weight: bold; text-align:right">153,977</td>
<td style="font-weight: bold; text-align:right;"></td>
<td style="font-weight: bold; text-align:right;">29,155 </td>
<td style="font-weight: bold;
                                    text-align:right;"></td>
<td style="font-weight: bold; text-align:right">70,842</td>
<td style="font-weight: bold; text-align:right;"></td>
<td style="text-align:right;font-weight:bold;">53,980</td>
<td style="font-weight: bold; text-align:right">1,053</td>
<td style="font-weight: bold; text-align:right">2,359</td>
<td style="font-weight: bold; text-align:right">447</td>
<td style="font-weight: bold; text-align:right">1,384,633</td>
<td style="font-weight: bold; text-align:right">21,216</td>
<td style="font-weight: bold; text-align:right"><a href="/world-population/france-population/">65,264,696</a> </td>
<td data-continent="Europe" style="display:none">Europe</td>
<td>424</td><td>2,239</td><td>47</td>
</tr>
<tr style="">
<td style="font-size:12px;color: grey;text-align:center;vertical-align:middle;">13</td>
<td style="font-weight: bold; font-size:15px; text-align:left;"><a class="mt_a" href="country/chile/">Chile</a></td>
<td style="font-weight: bold; text-align:right">134,150</td>
<td style="font-weight: bold; text-align:right;"></td>
<td style="font-weight: bold; text-align:right;">2,190 </td>
<td style="font-weight: bold;
                                    text-align:right;"></td>
<td style="font-weight: bold; text-align:right">95,631</td>
<td style="font-weight: bold; text-align:right;"></td>
<td style="text-align:right;font-weight:bold;">36,329</td>
<td style="font-weight: bold; text-align:right">1,558</td>
<td style="font-weight: bold; text-align:right">7,021</td>
<td style="font-weight: bold; text-align:right">115</td>
<td style="font-weight: bold; text-align:right">708,773</td>
<td style="font-weight: bold; text-align:right">37,098</td>
<td style="font-weight: bold; text-align:right"><a href="/world-population/chile-population/">19,105,644</a> </td>
<td data-continent="South America" style="display:none">South America</td>
<td>142</td><td>8,724</td><td>27</td>
</tr>
<tr style="">
<td style="font-size:12px;color: grey;text-align:center;vertical-align:middle;">14</td>

In [24]:
from bs4 import BeautifulSoup
import requests

res=requests.get(f"https://www.worldometers.info/coronavirus/",'html.parser')
data=res.text
soup=BeautifulSoup(data,'lxml')

table_tag=soup.find('table')
table_tags=table_tag.findAll('tr')
#table_tags
#make list to add data
#table_tag=table_tag[1:-5]
data_list=[]
for x in table_tags:
    data_list.append(x.get_text())
    
data_list[0].split()

['#',
 'Country,Other',
 'TotalCases',
 'NewCases',
 'TotalDeaths',
 'NewDeaths',
 'TotalRecovered',
 'NewRecovered',
 'ActiveCases',
 'Serious,Critical',
 'Tot',
 'Cases/1M',
 'pop',
 'Deaths/1M',
 'pop',
 'TotalTests',
 'Tests/',
 '1M',
 'pop',
 'Population',
 'Continent',
 '1',
 'Caseevery',
 'X',
 'ppl1',
 'Deathevery',
 'X',
 'ppl1',
 'Testevery',
 'X',
 'ppl']

In [11]:
from bs4 import BeautifulSoup
import requests

finaldata=[]
res=requests.get(f"https://www.worldometers.info/coronavirus/",'html.parser')
data=res.text
soup=BeautifulSoup(data,'lxml')

table_tag=soup.find('table')
table_tags=table_tag.findAll('tr')
table_tags=table_tags[0:-1] # used to select rows of table
#make list to add data
data_list=[]

for x in table_tags:
    data_list.append(x.get_text())
    
#data_list[0].split('\n')

for y in range(len(data_list)):
    finaldata.append(data_list[y][0:-1].split())
    
finaldata

[['#',
  'Country,Other',
  'TotalCases',
  'NewCases',
  'TotalDeaths',
  'NewDeaths',
  'TotalRecovered',
  'NewRecovered',
  'ActiveCases',
  'Serious,Critical',
  'Tot',
  'Cases/1M',
  'pop',
  'Deaths/1M',
  'pop',
  'TotalTests',
  'Tests/',
  '1M',
  'pop',
  'Population',
  'Continent',
  '1',
  'Caseevery',
  'X',
  'ppl1',
  'Deathevery',
  'X',
  'ppl1',
  'Testevery',
  'X',
  'ppl'],
 ['North',
  'America',
  '2,282,752',
  '+4,272',
  '135,758',
  '+221',
  '930,372',
  '+3,075',
  '1,216,622',
  '19,441',
  'North',
  'America'],
 ['South',
  'America',
  '1,146,755',
  '+285',
  '51,046',
  '+824',
  '531,548',
  '+184',
  '564,161',
  '11,783',
  'South',
  'America'],
 ['Europe',
  '2,104,149',
  '+9,841',
  '179,089',
  '+146',
  '1,087,015',
  '+4,887',
  '838,045',
  '7,166',
  'Europe'],
 ['Asia',
  '1,372,213',
  '+10,984',
  '35,199',
  '+174',
  '825,126',
  '+2,830',
  '511,888',
  '14,881',
  'Asia'],
 ['Africa',
  '192,236',
  '+118',
  '5,218',
  '+3',
  '84,925',
  '+6',
  '102,093',
  '470',
  'Africa'],
 ['Oceania',
  '8,875',
  '+5',
  '124',
  '8,293',
  '+4',
  '458',
  '3',
  'Australia/Oceania'],
 ['721', '15', '651', '55', '4'],
 ['World',
  '7,107,701',
  '+25,505',
  '406,449',
  '+1,368',
  '3,467,930',
  '+10,986',
  '3,233,322',
  '53,748',
  '912',
  '52.1',
  'All'],
 ['1',
  'USA',
  '2,007,449',
  '112,469',
  '761,708',
  '1,133,272',
  '16,923',
  '6,067',
  '340',
  '21,291,677',
  '64,349',
  '330,880,530',
  'North',
  'America',
  '1652,94216'],
 ['2',
  'Brazil',
  '691,962',
  '37,312',
  '+813',
  '302,084',
  '352,566',
  '8,318',
  '3,257',
  '176',
  '999,836',
  '4,706',
  '212,463,372',
  'South',
  'America',
  '3075,694212'],
 ['3',
  'Russia',
  '476,658',
  '+8,985',
  '5,971',
  '+112',
  '230,688',
  '+3,957',
  '239,999',
  '2,300',
  '3,266',
  '41',
  '13,000,000',
  '89,083',
  '145,930,700',
  'Europe',
  '30624,44011'],
 ['4',
  'Spain',
  '288,630',
  '27,136',
  'N/A',
  'N/A',
  'N/A',
  '617',
  '6,173',
  '580',
  '4,465,338',
  '95,508',
  '46,753,690',
  'Europe',
  '1621,72310'],
 ['5',
  'UK',
  '286,194',
  '40,542',
  'N/A',
  'N/A',
  'N/A',
  '604',
  '4,217',
  '597',
  '5,581,073',
  '82,239',
  '67,863,688',
  'Europe',
  '2371,67412'],
 ['6',
  'India',
  '258,090',
  '+604',
  '7,207',
  '124,095',
  '+247',
  '126,788',
  '8,944',
  '187',
  '5',
  '4,774,434',
  '3,462',
  '1,379,122,578',
  'Asia',
  '5,344191,359289'],
 ['7',
  'Italy',
  '234,998',
  '33,899',
  '165,837',
  '35,262',
  '287',
  '3,886',
  '561',
  '4,236,535',
  '70,063',
  '60,467,085',
  'Europe',
  '2571,78414'],
 ['8',
  'Peru',
  '196,515',
  '5,465',
  '86,219',
  '104,831',
  '1,062',
  '5,966',
  '166',
  '1,191,956',
  '36,185',
  '32,941,004',
  'South',
  'America',
  '1686,02828'],
 ['9',
  'Germany',
  '185,869',
  '8,776',
  '169,600',
  '+500',
  '7,493',
  '568',
  '2,219',
  '105',
  '4,348,880',
  '51,916',
  '83,767,456',
  'Europe',
  '4519,54519'],
 ['10',
  'Iran',
  '171,789',
  '8,281',
  '134,349',
  '29,159',
  '2,596',
  '2,047',
  '99',
  '1,084,857',
  '12,927',
  '83,921,387',
  'Asia',
  '48910,13477'],
 ['11',
  'Turkey',
  '170,132',
  '4,692',
  '137,969',
  '27,471',
  '613',
  '2,019',
  '56',
  '2,338,593',
  '27,748',
  '84,279,639',
  'Asia',
  '49517,96236'],
 ['12',
  'France',
  '153,977',
  '29,155',
  '70,842',
  '53,980',
  '1,053',
  '2,359',
  '447',
  '1,384,633',
  '21,216',
  '65,264,696',
  'Europe',
  '4242,23947'],
 ['13',
  'Chile',
  '134,150',
  '2,190',
  '95,631',
  '36,329',
  '1,558',
  '7,021',
  '115',
  '708,773',
  '37,098',
  '19,105,644',
  'South',
  'America',
  '1428,72427'],
 ['14',
  'Mexico',
  '117,103',
  '+3,484',
  '13,699',
  '+188',
  '84,419',
  '+2,875',
  '18,985',
  '378',
  '909',
  '106',
  '336,395',
  '2,611',
  '128,844,230',
  'North',
  'America',
  '1,1009,405383'],
 ['15',
  'Pakistan',
  '103,671',
  '+4,728',
  '2,067',
  '+65',
  '34,355',
  '+890',
  '67,249',
  '111',
  '470',
  '9',
  '705,833',
  '3,200',
  '220,591,553',
  'Asia',
  '2,128106,721313'],
 ['16',
  'Saudi',
  'Arabia',
  '101,914',
  '712',
  '72,817',
  '28,385',
  '1,564',
  '2,931',
  '20',
  '958,237',
  '27,554',
  '34,776,977',
  'Asia',
  '34148,84436'],
 ['17',
  'Canada',
  '95,699',
  '7,800',
  '54,233',
  '33,666',
  '1,816',
  '2,537',
  '207',
  '1,896,822',
  '50,286',
  '37,720,832',
  'North',
  'America',
  '3944,83620'],
 ['18',
  'Qatar',
  '68,790',
  '54',
  '44,338',
  '24,398',
  '245',
  '24,500',
  '19',
  '255,533',
  '91,008',
  '2,807,805',
  'Asia',
  '4151,99611'],
 ['19',
  'Bangladesh',
  '68,504',
  '+2,735',
  '930',
  '+42',
  '14,560',
  '+657',
  '53,014',
  '1',
  '416',
  '6',
  '410,841',
  '2,496',
  '164,582,631',
  'Asia',
  '2,403176,971401'],
 ['20',
  'Belgium',
  '59,348',
  '+122',
  '9,606',
  '+11',
  '16,315',
  '+24',
  '33,427',
  '116',
  '5,122',
  '829',
  '949,675',
  '81,964',
  '11,586,489',
  'Europe',
  '1951,20612'],
 ['21',
  'Belarus',
  '48,630',
  '269',
  '23,647',
  '24,714',
  '92',
  '5,146',
  '28',
  '622,313',
  '65,857',
  '9,449,509',
  'Europe',
  '19435,12815'],
 ['22',
  'South',
  'Africa',
  '48,285',
  '998',
  '24,364',
  '22,923',
  '208',
  '815',
  '17',
  '920,064',
  '15,526',
  '59,258,991',
  'Africa',
  '1,22759,37864'],
 ['23',
  'Netherlands',
  '47,574',
  '6,013',
  'N/A',
  'N/A',
  'N/A',
  '97',
  '2,777',
  '351',
  '388,113',
  '22,654',
  '17,132,558',
  'Europe',
  '3602,84944'],
 ['24',
  'Sweden',
  '44,730',
  '4,659',
  'N/A',
  'N/A',
  'N/A',
  '198',
  '4,431',
  '462',
  '275,500',
  '27,290',
  '10,095,291',
  'Europe',
  '2262,16737'],
 ['25',
  'Ecuador',
  '43,120',
  '3,621',
  '21,020',
  '18,479',
  '222',
  '2,447',
  '205',
  '127,414',
  '7,229',
  '17,624,879',
  'South',
  'America',
  '4094,867138'],
 ['26',
  'Colombia',
  '39,236',
  '1,259',
  '15,322',
  '22,655',
  '335',
  '772',
  '25',
  '410,719',
  '8,077',
  '50,847,406',
  'South',
  'America',
  '1,29640,387124'],
 ['27',
  'UAE',
  '38,808',
  '276',
  '21,806',
  '16,726',
  '1',
  '3,927',
  '28',
  '2,500,000',
  '252,973',
  '9,882,493',
  'Asia',
  '25535,8064'],
 ['28',
  'Singapore',
  '38,296',
  '+386',
  '25',
  '24,886',
  '13,385',
  '3',
  '6,549',
  '4',
  '408,495',
  '69,859',
  '5,847,399',
  'Asia',
  '153233,89614'],
 ['29',
  'Portugal',
  '34,693',
  '1,479',
  '20,995',
  '12,219',
  '58',
  '3,402',
  '145',
  '873,998',
  '85,699',
  '10,198,446',
  'Europe',
  '2946,89612'],
 ['30',
  'Egypt',
  '34,079',
  '1,237',
  '8,961',
  '23,881',
  '41',
  '333',
  '12',
  '135,000',
  '1,321',
  '102,199,634',
  'Africa',
  '2,99982,619757'],
 ['31',
  'Indonesia',
  '32,033',
  '+847',
  '1,883',
  '+32',
  '10,904',
  '+406',
  '19,246',
  '117',
  '7',
  '412,980',
  '1,511',
  '273,334,499',
  'Asia',
  '8,533145,159662'],
 ['32',
  'Kuwait',
  '31,848',
  '264',
  '20,205',
  '11,379',
  '196',
  '7,465',
  '62',
  '315,285',
  '73,901',
  '4,266,300',
  'Asia',
  '13416,16014'],
 ['33',
  'Switzerland',
  '30,965',
  '1,921',
  '28,700',
  '344',
  '28',
  '3,580',
  '222',
  '423,468',
  '48,952',
  '8,650,592',
  'Europe',
  '2794,50320'],
 ['34',
  'Ukraine',
  '27,462',
  '+463',
  '797',
  '+9',
  '12,195',
  '+141',
  '14,470',
  '304',
  '628',
  '18',
  '431,085',
  '9,854',
  '43,748,704',
  'Europe',
  '1,59354,892101'],
 ['35',
  'Poland',
  '26,780',
  '+219',
  '1,161',
  '+4',
  '12,998',
  '+143',
  '12,621',
  '160',
  '708',
  '31',
  '1,056,396',
  '27,911',
  '37,849,071',
  'Europe',
  '1,41332,60036'],
 ['36',
  'Ireland',
  '25,201',
  '1,679',
  '22,698',
  '824',
  '36',
  '5,107',
  '340',
  '348,416',
  '70,613',
  '4,934,162',
  'Europe',
  '1962,93914'],
 ['37',
  'Argentina',
  '22,794',
  '664',
  '6,909',
  '15,221',
  '274',
  '505',
  '15',
  '193,923',
  '4,293',
  '45,168,963',
  'South',
  'America',
  '1,98268,026233'],
 ['38',
  'Philippines',
  '22,474',
  '+579',
  '1,011',
  '+8',
  '4,637',
  '+107',
  '16,826',
  '82',
  '205',
  '9',
  '430,081',
  '3,928',
  '109,483,597',
  'Asia',
  '4,872108,292255'],
 ['39',
  'Afghanistan',
  '20,917',
  '+575',
  '369',
  '+12',
  '2,171',
  '+296',
  '18,377',
  '19',
  '538',
  '9',
  '48,305',
  '1,243',
  '38,865,373',
  'Asia',
  '1,858105,326805'],
 ['40',
  'Romania',
  '20,479',
  '1,334',
  '+1',
  '14,638',
  '4,507',
  '144',
  '1,064',
  '69',
  '503,200',
  '26,147',
  '19,244,947',
  'Europe',
  '94014,42638'],
 ['41',
  'Dominican',
  'Republic',
  '19,600',
  '538',
  '12,007',
  '7,055',
  '110',
  '1,808',
  '50',
  '94,511',
  '8,718',
  '10,840,829',
  'North',
  'America',
  '55320,150115'],
 ['42',
  'Israel',
  '17,915',
  '+52',
  '298',
  '15,102',
  '+11',
  '2,515',
  '27',
  '1,948',
  '32',
  '662,916',
  '72,075',
  '9,197,590',
  'Asia',
  '51330,86414'],
 ['43',
  'Japan',
  '17,141',
  '916',
  '15,139',
  '1,086',
  '98',
  '136',
  '7',
  '314,483',
  '2,486',
  '126,499,051',
  'Asia',
  '7,380138,099402'],
 ['44',
  'Austria',
  '16,902',
  '672',
  '15,793',
  '437',
  '17',
  '1,877',
  '75',
  '494,761',
  '54,954',
  '9,003,169',
  'Europe',
  '53313,39818'],
 ['45',
  'Oman',
  '16,882',
  '75',
  '3,451',
  '13,356',
  '75',
  '3,312',
  '15',
  '108,679',
  '21,322',
  '5,097,088',
  'Asia',
  '30267,96147'],
 ['46',
  'Panama',
  '16,425',
  '393',
  '10,218',
  '5,814',
  '84',
  '3,811',
  '91',
  '72,697',
  '16,867',
  '4,310,139',
  'North',
  'America',
  '26210,96759'],
 ['47',
  'Bahrain',
  '14,763',
  '26',
  '9,468',
  '5,269',
  '13',
  '8,700',
  '15',
  '367,056',
  '216,308',
  '1,696,917',
  'Asia',
  '11565,2665'],
 ['48',
  'Bolivia',
  '13,643',
  '+285',
  '465',
  '+11',
  '2,086',
  '+184',
  '11,092',
  '3',
  '1,170',
  '40',
  '37,276',
  '3,196',
  '11,662,351',
  'South',
  'America',
  '85525,080313'],
 ['49',
  'Armenia',
  '13,325',
  '+195',
  '211',
  '+11',
  '4,099',
  '+85',
  '9,015',
  '10',
  '4,497',
  '71',
  '70,000',
  '23,625',
  '2,962,906',
  'Asia',
  '22214,04242'],
 ['50',
  'Kazakhstan',
  '12,859',
  '+165',
  '56',
  '+3',
  '7,376',
  '5,427',
  '62',
  '685',
  '3',
  '965,089',
  '51,439',
  '18,761,857',
  'Asia',
  '1,459335,03319'],
 ['51',
  'Nigeria',
  '12,486',
  '354',
  '3,959',
  '8,173',
  '7',
  '61',
  '2',
  '76,802',
  '373',
  '205,766,196',
  'Africa',
  '16,480581,2602,679'],
 ['52',
  'Iraq',
  '12,366',
  '346',
  '5,186',
  '6,834',
  '69',
  '308',
  '9',
  '303,053',
  '7,547',
  '40,157,701',
  'Asia',
  '3,247116,063133'],
 ['53',
  'Denmark',
  '11,948',
  '589',
  '10,755',
  '604',
  '15',
  '2,063',
  '102',
  '706,442',
  '121,991',
  '5,790,943',
  'Europe',
  '4859,8328'],
 ['54',
  'Serbia',
  '11,823',
  '249',
  '11,348',
  '226',
  '15',
  '1,353',
  '28',
  '272,502',
  '31,181',
  '8,739,407',
  'Europe',
  '73935,09832'],
 ['55',
  'S.',
  'Korea',
  '11,814',
  '+38',
  '273',
  '10,563',
  '+11',
  '978',
  '15',
  '230',
  '5',
  '1,018,214',
  '19,861',
  '51,266,523',
  'Asia',
  '4,339187,78950'],
 ['56',
  'Algeria',
  '10,154',
  '707',
  '6,717',
  '2,730',
  '24',
  '232',
  '16',
  '43,796,100',
  'Africa',
  '4,31361,946'],
 ['57',
  'Moldova',
  '9,700',
  '346',
  '+5',
  '5,738',
  '+100',
  '3,616',
  '318',
  '2,404',
  '86',
  '63,328',
  '15,697',
  '4,034,514',
  'Europe',
  '41611,66064'],
 ['58',
  'Ghana',
  '9,638',
  '44',
  '3,636',
  '5,958',
  '3',
  '311',
  '1',
  '233,734',
  '7,533',
  '31,026,938',
  'Africa',
  '3,219705,158133'],
 ['59',
  'Czechia',
  '9,629',
  '+1',
  '328',
  '+1',
  '6,896',
  '+5',
  '2,405',
  '9',
  '899',
  '31',
  '473,747',
  '44,243',
  '10,707,772',
  'Europe',
  '1,11232,64623'],
 ['60',
  'Norway',
  '8,547',
  '238',
  '8,138',
  '171',
  '5',
  '1,577',
  '44',
  '257,303',
  '47,486',
  '5,418,531',
  'Europe',
  '63422,76721'],
 ['61',
  'Malaysia',
  '8,329',
  '+7',
  '117',
  '6,694',
  '+20',
  '1,518',
  '6',
  '258',
  '4',
  '610,038',
  '18,864',
  '32,338,393',
  'Asia',
  '3,883276,39753'],
 ['62',
  'Morocco',
  '8,250',
  '+26',
  '208',
  '7,370',
  '+6',
  '672',
  '15',
  '224',
  '6',
  '316,561',
  '8,583',
  '36,881,658',
  'Africa',
  '4,471177,316117'],
 ['63',
  'Cameroon',
  '7,908',
  '212',
  '4,735',
  '2,961',
  '28',
  '298',
  '8',
  '26,497,531',
  'Africa',
  '3,351124,988'],
 ['64',
  'Azerbaijan',
  '7,553',
  '88',
  '4,149',
  '3,316',
  '66',
  '745',
  '9',
  '328,385',
  '32,407',
  '10,133,277',
  'Asia',
  '1,342115,15131'],
 ['65',
  'Australia',
  '7,265',
  '+5',
  '102',
  '6,706',
  '+3',
  '457',
  '3',
  '285',
  '4',
  '1,632,116',
  '64,054',
  '25,480,378',
  'Australia/Oceania',
  '3,507249,80816'],
 ['66',
  'Guatemala',
  '7,055',
  '+263',
  '252',
  '+22',
  '1,261',
  '+128',
  '5,542',
  '5',
  '394',
  '14',
  '31,427',
  '1,756',
  '17,892,493',
  'North',
  'America',
  '2,53671,002569'],
 ['67',
  'Finland',
  '7,001',
  '+20',
  '323',
  '5,800',
  '878',
  '6',
  '1,264',
  '58',
  '203,439',
  '36,721',
  '5,540,198',
  'Europe',
  '79117,15227'],
 ['68',
  'Honduras',
  '6,327',
  '+172',
  '258',
  '+8',
  '712',
  '+15',
  '5,357',
  '13',
  '639',
  '26',
  '21,540',
  '2,177',
  '9,893,859',
  'North',
  'America',
  '1,56438,348459'],
 ['69',
  'Sudan',
  '6,081',
  '359',
  '2,014',
  '3,708',
  '139',
  '8',
  '401',
  '9',
  '43,775,253',
  'Africa',
  '7,199121,937109,165'],
 ['70',
  'Tajikistan',
  '4,529',
  '48',
  '2,673',
  '1,808',
  '476',
  '5',
  '9,522,265',
  'Asia',
  '2,103198,381'],
 ['71',
  'Uzbekistan',
  '4,352',
  '+21',
  '17',
  '3,354',
  '981',
  '7',
  '130',
  '0.5',
  '748,555',
  '22,387',
  '33,436,477',
  'Asia',
  '7,6831,966,85245'],
 ['72',
  'Senegal',
  '4,328',
  '49',
  '2,588',
  '1,691',
  '15',
  '259',
  '3',
  '49,180',
  '2,943',
  '16,711,294',
  'Africa',
  '3,861341,047340'],
 ['73',
  'Djibouti',
  '4,207',
  '28',
  '1,877',
  '2,302',
  '4,262',
  '28',
  '35,165',
  '35,627',
  '987,030',
  'Africa',
  '23535,25128'],
 ['74',
  'Guinea',
  '4,117',
  '23',
  '2,877',
  '1,217',
  '24',
  '314',
  '2',
  '14,407',
  '1,099',
  '13,106,296',
  'Africa',
  '3,183569,839910'],
 ['75',
  'DRC',
  '4,106',
  '+90',
  '88',
  '+3',
  '537',
  '3,481',
  '46',
  '1.0',
  '89,353,804',
  'Africa',
  '21,7621,015,384'],
 ['76',
  'Luxembourg',
  '4,039',
  '110',
  '3,899',
  '30',
  '1',
  '6,459',
  '176',
  '88,051',
  '140,818',
  '625,281',
  'Europe',
  '1555,6847'],
 ['77',
  'Hungary',
  '4,014',
  '+6',
  '548',
  '+2',
  '2,284',
  '+5',
  '1,182',
  '21',
  '415',
  '57',
  '210,749',
  '21,813',
  '9,661,789',
  'Europe',
  '2,40717,63146'],
 ['78',
  'Ivory',
  'Coast',
  '3,739',
  '36',
  '1,818',
  '1,885',
  '142',
  '1',
  '31,549',
  '1,198',
  '26,330,544',
  'Africa',
  '7,042731,404835'],
 ['79',
  'Nepal',
  '3,448',
  '13',
  '467',
  '2,968',
  '118',
  '0.4',
  '241,254',
  '8,290',
  '29,100,465',
  'Asia',
  '8,4402,238,497121'],
 ['80',
  'Haiti',
  '3,334',
  '+262',
  '51',
  '+1',
  '24',
  '3,259',
  '293',
  '4',
  '7,357',
  '646',
  '11,393,320',
  'North',
  'America',
  '3,417223,3981,549'],
 ['81',
  'Thailand',
  '3,119',
  '+7',
  '58',
  '2,973',
  '+1',
  '88',
  '1',
  '45',
  '0.8',
  '468,175',
  '6,708',
  '69,789,262',
  'Asia',
  '22,3761,203,263149'],
 ['82',
  'El',
  'Salvador',
  '3,104',
  '+89',
  '55',
  '+2',
  '1,361',
  '+56',
  '1,688',
  '92',
  '479',
  '8',
  '108,924',
  '16,798',
  '6,484,160',
  'North',
  'America',
  '2,089117,89460'],
 ['83',
  'Gabon',
  '3,101',
  '21',
  '833',
  '2,247',
  '13',
  '1,396',
  '9',
  '16,730',
  '7,529',
  '2,221,930',
  'Africa',
  '717105,806133'],
 ['84',
  'North',
  'Macedonia',
  '3,025',
  '153',
  '1,646',
  '1,226',
  '34',
  '1,452',
  '73',
  '36,325',
  '17,436',
  '2,083,379',
  'Europe',
  '68913,61757'],
 ['85',
  'Greece',
  '2,997',
  '180',
  '1,374',
  '1,443',
  '9',
  '287',
  '17',
  '193,929',
  '18,601',
  '10,425,978',
  'Europe',
  '3,47957,92254'],
 ['86',
  'Kenya',
  '2,767',
  '84',
  '752',
  '1,931',
  '7',
  '52',
  '2',
  '97,340',
  '1,813',
  '53,686,542',
  'Africa',
  '19,402639,126552'],
 ['87',
  'Bulgaria',
  '2,727',
  '+16',
  '160',
  '1,548',
  '1,019',
  '12',
  '392',
  '23',
  '90,329',
  '12,994',
  '6,951,380',
  'Europe',
  '2,54943,44677'],
 ['88',
  'Bosnia',
  'and',
  'Herzegovina',
  '2,606',
  '159',
  '1,968',
  '479',
  '4',
  '794',
  '48',
  '69,654',
  '21,223',
  '3,281,977',
  'Europe',
  '1,25920,64147'],
 ['89',
  'Venezuela',
  '2,377',
  '22',
  '487',
  '1,868',
  '84',
  '0.8',
  '1,343,336',
  '47,233',
  '28,440,650',
  'South',
  'America',
  '11,9651,292,75721'],
 ['90',
  'Somalia',
  '2,334',
  '83',
  '441',
  '1,810',
  '2',
  '147',
  '5',
  '15,860,043',
  'Africa',
  '6,795191,085'],
 ['91',
  'Croatia',
  '2,247',
  '104',
  '2,126',
  '17',
  '2',
  '547',
  '25',
  '68,740',
  '16,738',
  '4,106,705',
  'Europe',
  '1,82839,48860'],
 ['92',
  'Cuba',
  '2,191',
  '83',
  '1,862',
  '246',
  '3',
  '193',
  '7',
  '118,488',
  '10,461',
  '11,327,028',
  'North',
  'America',
  '5,170136,47096'],
 ['93',
  'Mayotte',
  '2,079',
  '25',
  '1,523',
  '531',
  '12',
  '7,634',
  '92',
  '8,150',
  '29,926',
  '272,336',
  'Africa',
  '13110,89333'],
 ['94',
  'Kyrgyzstan',
  '2,032',
  '+25',
  '23',
  '+1',
  '1,445',
  '+20',
  '564',
  '5',
  '312',
  '4',
  '127,051',
  '19,496',
  '6,516,817',
  'Asia',
  '3,207283,34051'],
 ['95',
  'Ethiopia',
  '2,020',
  '27',
  '344',
  '1,649',
  '32',
  '18',
  '0.2',
  '142,960',
  '1,246',
  '114,755,497',
  'Africa',
  '56,8104,250,204803'],
 ['96',
  'Estonia',
  '1,940',
  '+1',
  '69',
  '1,683',
  '+2',
  '188',
  '1,463',
  '52',
  '90,620',
  '68,316',
  '1,326,481',
  'Europe',
  '68419,22415'],
 ['97',
  'Maldives',
  '1,903',
  '8',
  '827',
  '1,068',
  '9',
  '3,525',
  '15',
  '28,940',
  '53,604',
  '539,886',
  'Asia',
  '28467,48619'],
 ['98',
  'Sri',
  'Lanka',
  '1,835',
  '11',
  '990',
  '+49',
  '834',
  '1',
  '86',
  '0.5',
  '76,957',
  '3,595',
  '21,407,678',
  'Asia',
  '11,6661,946,153278'],
 ['99',
  'Iceland',
  '1,807',
  '10',
  '1,794',
  '3',
  '5,298',
  '29',
  '62,795',
  '184,094',
  '341,103',
  'Europe',
  '18934,1105'],
 ['100',
  'Lithuania',
  '1,720',
  '+6',
  '71',
  '1,331',
  '+3',
  '318',
  '17',
  '631',
  '26',
  '335,686',
  '123,219',
  '2,724,301',
  'Europe',
  '1,58438,3708'],
 ['101',
  'CAR',
  '1,634',
  '5',
  '38',
  '1,591',
  '339',
  '1',
  '15,881',
  '3,292',
  '4,823,971',
  'Africa',
  '2,952964,794304'],
 ['102',
  'Mali',
  '1,533',
  '90',
  '873',
  '570',
  '76',
  '4',
  '3,483',
  '172',
  '20,206,890',
  'Africa',
  '13,181224,5215,802'],
 ['103',
  'Slovakia',
  '1,530',
  '+2',
  '28',
  '1,396',
  '+7',
  '106',
  '280',
  '5',
  '189,575',
  '34,724',
  '5,459,483',
  'Europe',
  '3,568194,98229'],
 ['104',
  'New',
  'Zealand',
  '1,504',
  '22',
  '1,482',
  '+1',
  '0',
  '301',
  '4',
  '294,848',
  '58,945',
  '5,002,100',
  'Australia/Oceania',
  '3,326227,36817'],
 ['105',
  'Slovenia',
  '1,485',
  '109',
  '1,359',
  '17',
  '714',
  '52',
  '84,537',
  '40,664',
  '2,078,921',
  'Europe',
  '1,40019,07325'],
 ['106',
  'Guinea-Bissau',
  '1,368',
  '12',
  '153',
  '1,203',
  '696',
  '6',
  '1,500',
  '764',
  '1,964,631',
  'Africa',
  '1,436163,7191,310'],
 ['107',
  'Lebanon',
  '1,331',
  '30',
  '768',
  '533',
  '6',
  '195',
  '4',
  '95,154',
  '13,937',
  '6,827,207',
  'Asia',
  '5,129227,57472'],
 ['108',
  'Costa',
  'Rica',
  '1,318',
  '10',
  '704',
  '604',
  '4',
  '259',
  '2',
  '29,449',
  '5,784',
  '5,091,112',
  'North',
  'America',
  '3,863509,111173'],
 ['109',
  'South',
  'Sudan',
  '1,317',
  '14',
  '6',
  '1,297',
  '118',
  '1',
  '3,356',
  '300',
  '11,185,064',
  'Africa',
  '8,493798,9333,333'],
 ['110',
  'Equatorial',
  'Guinea',
  '1,306',
  '12',
  '200',
  '1,094',
  '933',
  '9',
  '8,268',
  '5,908',
  '1,399,406',

In [4]:
import csv

len_list=len(finaldata)
try:
    with open("Project3.csv","w") as csvFile:
        for i in range(len_list):
            w=csv.writer(csvFile)
            w.writerow(finaldata[i])
        print("Succeed")
except:
    print("Error occured")

Succeed

In [1]:
import pandas as p

obj=p.read_csv("Project1.csv",nrows=15)#Project 3 rakheko maa error dekhako xa
obj

,#,"Country,Other",TotalCases,NewCases,TotalDeaths,NewDeaths,TotalRecovered,NewRecovered,ActiveCases,"Serious,Critical",...,1,Caseevery,X,ppl1,Deathevery,X.1,ppl1.1,Testevery,X.2,ppl
0,North,America,"2,282,663","+4,183","135,758",+221,"930,353","+3,056","1,216,552","19,428",...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,South,America,"1,146,755",+285,"51,046",+824,"531,548",+184,"564,161","11,783",...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,Europe,"2,104,007","+9,699","179,078",+135,"1,086,991","+4,863","837,938","7,164",Europe,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,Asia,"1,368,045","+6,816","35,117",+92,"823,936","+1,640","508,992","14,880",Asia,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,Africa,"192,118","5,215","84,919","101,984",469,Africa,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5,Oceania,"8,875",+5,124,"8,293",+4,458,3,Australia/Oceania,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
6,721,15,651,55,4,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
7,World,"7,103,184","+20,988","406,353","+1,272","3,466,691","+9,747","3,230,140","53,731",911,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
8,1,USA,"2,007,449","112,469","761,708","1,133,272","16,923","6,067",340,"21,291,677",...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
9,2,Brazil,"691,962","37,312",+813,"302,084","352,566","8,318","3,257",176,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
10,3,Russia,"476,658","+8,985","5,971",+112,"230,688","+3,957","239,999","2,300",...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
11,4,Spain,"288,630","27,136",NaN,NaN,NaN,617,"6,173",580,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
12,5,UK,"286,194","40,542",NaN,NaN,NaN,604,"4,217",597,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
13,6,India,"258,090",+604,"7,207","124,095",+247,"126,788","8,944",187,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
14,7,Italy,"234,998","33,899","165,837","35,262",287,"3,886",561,"4,236,535",...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [25]:
import pandas as p

df=p.read_csv("Project1.csv",usecols=['#','Country,Other','TotalCases','TotalDeaths','TotalRecovered','ActiveCases'],nrows=25)
df

,#,"Country,Other",TotalCases,TotalDeaths,TotalRecovered,ActiveCases
0,North,America,"2,282,663","135,758","930,353","1,216,552"
1,South,America,"1,146,755","51,046","531,548","564,161"
2,Europe,"2,104,007","+9,699",+135,"+4,863","7,164"
3,Asia,"1,368,045","+6,816",+92,"+1,640","14,880"
4,Africa,"192,118","5,215","101,984",Africa,NaN
5,Oceania,"8,875",+5,"8,293",458,Australia/Oceania
6,721,15,651,4,NaN,NaN
7,World,"7,103,184","+20,988","+1,272","+9,747","53,731"
8,1,USA,"2,007,449","761,708","16,923",340
9,2,Brazil,"691,962",+813,"352,566","3,257"
10,3,Russia,"476,658","5,971","230,688","239,999"
11,4,Spain,"288,630",NaN,NaN,"6,173"
12,5,UK,"286,194",NaN,NaN,"4,217"
13,6,India,"258,090","7,207",+247,"8,944"
14,7,Italy,"234,998","165,837",287,561
15,8,Peru,"196,515","86,219","1,062",166
16,9,Germany,"185,869","169,600","7,493","2,219"
17,10,Iran,"171,789","134,349","2,596",99
18,11,Turkey,"170,132","137,969",613,56
19,12,France,"153,977","70,842","1,053",447
20,13,Chile,"134,150","95,631","1,558",115
21,14,Mexico,"117,103","13,699","84,419","18,985"
22,15,Pakistan,"103,671","2,067","34,355","67,249"
23,16,Saudi,Arabia,712,"28,385","2,931"
24,17,Canada,"95,699","54,233","1,816",207

In [ ]:


#iloc[0:3,3:8] for row and col

#loc[2:8] searches rows only

In [ ]:
from matplotlib import pyplot as py

usecols=['#','Country,Other','TotalCases','TotalDeaths','TotalRecovered','ActiveCases'],